# Generated by Django 3.0.4 on 2021-03-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(default='customer', max_length=50),
            preserve_default=False,
        ),
    ]
